version: '3.8'

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-cpp-ce:latest
    ports:
      - 8081:8081
      - 8082:8082
    
  app:
    build: ./app
    extra_hosts:
      - artifactory:192.168.96.216

  conan:
    image: dkruger/conan-server:latest
    container_name: conan
    user: root
    ports:
      - 9300:9300