name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./app
      run: docker build -t conan_pkgr .
    - name: Run container
      run: docker run -d --name conan_pkgr conan_pkgr
    - name: Test
      run: docker exec -i conan_pkgr /bin/bash -c "conan profile show default"
    - name: Test
      run: docker exec -i conan_pkgr /bin/bash -c "cppcheck --enable=all --std=c++11 src --force"
    - name: Generate package
      run: docker exec -i conan_pkgr /bin/bash -c "mkdir -p build;cd build;time cmake ..;time cmake --build .;echo -e '\n';./bin/Helloworld;echo -e '\n';./bin/main"
    - name: Clean
      run: |
        docker stop conan_pkgr
        docker rm -f conan_pkgr