name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./app
      run: docker build -t conan_pkgr .
    - name: Generate package
      run: docker run -i --rm conan_pkgr /bin/bash -c "cd app;mkdir -p build;cmake ..;cmake --build .;./Helloworld"
